In [2]:
import pandas as pd

In [3]:
games_data = pd.read_csv('C:/Users/Alex/Desktop/Pandas/DataLessons/data/PS4_GamesSales.csv')
games_data

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,Grand Theft Auto V,2014.0,Action,Rockstar Games,6.06,9.71,0.60,3.02,19.39
1,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,6.18,6.05,0.41,2.44,15.09
2,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,5.26,6.21,0.21,2.26,13.94
3,Call of Duty: WWII,2017.0,Shooter,Activision,4.67,6.21,0.40,2.12,13.40
4,FIFA 18,2017.0,Sports,EA Sports,1.27,8.64,0.15,1.73,11.80
...,...,...,...,...,...,...,...,...,...
1029,Fallen Legion: Flames of Rebellion,NaN,Role-Playing,NaN,0.00,0.00,0.00,0.00,0.00
1030,Radial G Racing Revolved,2017.0,Racing,Tammeka Games,0.00,0.00,0.00,0.00,0.00
1031,The Mummy Demastered,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00
1032,Project Nimbus: Code Mirai,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00
1033,Battle Chef Brigade,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00

In [4]:
games_data.head(5)

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,Grand Theft Auto V,2014.0,Action,Rockstar Games,6.06,9.71,0.60,3.02,19.39
1,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,6.18,6.05,0.41,2.44,15.09
2,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,5.26,6.21,0.21,2.26,13.94
3,Call of Duty: WWII,2017.0,Shooter,Activision,4.67,6.21,0.40,2.12,13.40
4,FIFA 18,2017.0,Sports,EA Sports,1.27,8.64,0.15,1.73,11.80

In [6]:
# Выводим уникальыне значения + выводим в формат столбца
games_data['Genre'].unique()

array(['Action', 'Shooter', 'Action-Adventure', 'Sports', 'Role-Playing',
       'Misc', 'Platform', 'Racing', 'Fighting', 'Adventure', 'MMO',
       'Simulation', 'Music', 'Party', 'Strategy', 'Puzzle',
       'Visual Novel'], dtype=object)

In [8]:
# Выводим уникальыне значения + выводим в формат столбца
games_data['Genre'].unique().tolist()

['Action',
 'Shooter',
 'Action-Adventure',
 'Sports',
 'Role-Playing',
 'Misc',
 'Platform',
 'Racing',
 'Fighting',
 'Adventure',
 'MMO',
 'Simulation',
 'Music',
 'Party',
 'Strategy',
 'Puzzle',
 'Visual Novel']

In [9]:
# Выводим уникальыне значения + выводим в формат столбца
games_data['Genre'].value_counts()

Action              258
Role-Playing        123
Misc                123
Adventure            97
Shooter              89
Sports               71
Racing               48
Platform             46
Action-Adventure     40
Fighting             35
Strategy             28
Simulation           23
Music                19
Puzzle               16
MMO                   8
Visual Novel          8
Party                 2
Name: Genre, dtype: int64

In [13]:
# Посмотреть в категории жанр спорт, какие есть игры.  Чтобы сделать срез и убрать false еще раз надо отфильтровать. 
games_data[games_data['Genre'] == "Sports"]["Game"].unique().tolist()

['FIFA 18',
 'FIFA 17',
 'FIFA 16',
 'FIFA 15',
 'NBA 2K16',
 'NBA 2K17',
 'FIFA Soccer 14',
 'NBA 2K18',
 'Madden NFL 16',
 'Madden NFL 17',
 'Madden NFL 18',
 'NBA 2K15',
 'Madden NFL 15',
 'Rocket League',
 'NBA 2K14',
 'WWE 2K18',
 'EA Sports UFC 2',
 'WWE 2K16',
 'WWE 2K17',
 'WWE 2K15',
 'MLB The Show 17',
 'MLB The Show 18',
 'MLB 15: The Show',
 'Steep',
 'EA Sports UFC 3',
 'Madden NFL 25',
 'MLB 16: The Show',
 'Pro Evolution Soccer 2016',
 'Pro Evolution Soccer 2015',
 'Pro Evolution Soccer 2018',
 'Pro Evolution Soccer 2017',
 'MLB 14 The Show',
 'NHL 16',
 'NHL 15',
 'NHL 18',
 "Everybody's Golf",
 'Rory McIlroy PGA Tour',
 'NHL 17',
 'UEFA Euro 2016',
 'NBA Live 14',
 'NBA Live 15',
 'NBA Live 18',
 'Jikkyou Powerful Pro Baseball 2016',
 "Tony Hawk's Pro Skater 5",
 'NBA Live 16',
 'Pro Cycling Manager 2016',
 'The Golf Club',
 'Golf Club 2',
 'Rugby 15',
 'Don Bradman Cricket 14',
 'Rugby League Live 4',
 'Mark McMorris Infinite Air',
 'Dead or Alive Xtreme 3: Fortune',
 'Rugby 18',
 'MX vs. ATV Supercross Encore',
 'Handball 16',
 'Rugby World Cup 2015',
 'Rugby Challenge 3',
 'R.B.I. Baseball 2016',
 'Tour de France 2014',
 'R.B.I. Baseball 2017',
 "Dino Dini's Kick Off Revival",
 'Rugby League Live 3',
 'Blood Bowl 2',
 'Hustle Kings VR',
 'OlliOlli',
 'EA Sports PGA Tour',
 'OlliOlli 2: Welcome to Olliwood',
 'R.B.I. Baseball 15',
 'Jikkyou Powerful Pro Baseball Success Special',
 'Don Bradman Cricket 17']

In [16]:
# Вывод записи не спорт по жанру
games_data[(games_data['Genre'] != "Sports")&(games_data['North America'] < 5)]

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
3,Call of Duty: WWII,2017.0,Shooter,Activision,4.67,6.21,0.40,2.12,13.40
6,Uncharted (PS4),2016.0,Action,Sony Interactive Entertainment,4.49,3.93,0.21,1.70,10.33
7,Spider-Man (PS4),2018.0,Action-Adventure,Sony Interactive Entertainment,3.64,3.39,0.32,1.41,8.76
8,Call of Duty: Infinite Warfare,2016.0,Shooter,Activision,3.11,3.83,0.19,1.36,8.48
9,Fallout 4,2015.0,Role-Playing,Bethesda Softworks,2.91,3.97,0.27,1.34,8.48
...,...,...,...,...,...,...,...,...,...
1029,Fallen Legion: Flames of Rebellion,NaN,Role-Playing,NaN,0.00,0.00,0.00,0.00,0.00
1030,Radial G Racing Revolved,2017.0,Racing,Tammeka Games,0.00,0.00,0.00,0.00,0.00
1031,The Mummy Demastered,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00
1032,Project Nimbus: Code Mirai,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00
1033,Battle Chef Brigade,NaN,Action,NaN,0.00,0.00,0.00,0.00,0.00